### ISSUE TITLE
3720 breaks on 10.3

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#1320]
*Issue migrated from trac ticket [#1095](http://colloquy.info/project/ticket/1095)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Blocker | **priority:** Highest | **version:** 2.1 (Mac) | **status:** closed | **resolution:** Fixed | **keywords:** crash
___
#### 2007-09-14 03:35:37: Luke created the issue

Running Colloquy without problems until the 2.1 (3720) release, upon which Colloquy, upon starting the program, crashes automatically with the following error report every time:

dyld: /Downloaded Files/Colloquy.app/Contents/MacOS/Colloquy Undefined symbols:
/Downloaded Files/Colloquy.app/Contents/MacOS/Colloquy undefined reference to .objc_class_name_NSAffineTransform expected to be defined in Foundation

___
#### 2007-09-14 07:45:48: @xeenon edited the issue description

___
#### 2007-09-14 07:45:48: @xeenon changed title from *Colloquy Vers 2.1 auto-crash on program launch.* to *3720 breaks on 10.3*

___
#### 2007-09-14 07:45:48: @xeenon commented

The new release has busted 10.3 versions.

Please submit crash logs on relaunch of the application. They get sent to our server where we can look at all crashes and see which ones relate, are the same, and the seriousness of each crash.

___
#### 2007-09-19 15:05:26: dglazkov commented

If this helps any, running 3590 on 10.3.9 and have the same issue. However, I am able to occasionally avoid crashes by disabling auto-connect and connecting manually after the app starts.

___
#### 2007-09-23 00:29:30: net20 commented

[This page](http://developer.apple.com/documentation/Cocoa/Reference/Foundation/Classes/NSAffineTransform_Class/Reference/Reference.html) claims NSAffineTransform is defined in the Application Kit, not the Foundation, on 10.3.  Is this at all relevant?

___
#### 2007-09-25 16:49:46: alphabud commented

Please provide download in download folder of the last version that DID work on 10.3.9
The most recent version to download there is v2D14! This is ancient... and i would rather I did not have to go find a new client.

___
#### 2007-09-25 20:59:06: @xeenon commented

Replying to [comment:4 alphabud]:
> Please provide download in download folder of the last version that DID work on 10.3.9
> The most recent version to download there is v2D14! This is ancient... and i would rather I did not have to go find a new client.

http://colloquy.info/downloads/

Go to the nightlies folder. It's in there. Just look for the most recent date, which would be 2.26.07.

___
#### 2007-10-04 20:01:19: falsedan commented

http://colloquy.info/downloads/nightlies/2.26.07.zip

As someone who has only very recently heard of Colloquy, I am confused by the lack of information the website has about this bug. It would be nice if the Downloads page was changed to explicitly say "Requires 10.4 or higher, 10.3.9 users please use use the [previous release](http://colloquy.info/downloads/nightlies/2.26.07.zip)" instead of "Requires 10.3.9 or higher" until this ticket is resolved.

___
#### 2007-10-14 23:45:03: @xeenon changed status from *new* to *closed*

___
#### 2007-10-14 23:45:03: @xeenon changed resolution from ** to *fixed*

___
#### 2007-10-14 23:45:03: @xeenon commented

I think I fixed this in 3febeae5a8e34b39d5f8facbd4f74128151715e7.

___
#### 2007-10-16 13:51:27: falsedan commented

yeah launches for me now, thanks timothy
